use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Jonathan
Rockway
jrockway
Infinity
Interactive
Inc
http
Chris
Prather
chris
Florian
Ragwitz
rafl
Hans
Dieter
Pearcey
hdp
Jesse
Luehrs
doy
Karen
Etheridge
ether
Matt
Trout
mst
Rafael
Kitover
rkitover
Shawn
Moore
sartak
Stevan
Little
stevan
Tomas
Doran
bobtfish
Yuval
Kogman
nothingmuch
lib
MooseX
Traits
Util
